{
 "title": "Rudder's dashboard",
 "time": { "from": "2025-11-20T01:03:23.593Z", "to": "2025-11-20T18:44:35.135Z" },
 "panels": [
  { "title": "Global state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Global Compliance with Trend over last month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select global_compliance as 'Global compliance', TIMESTAMP\nfrom globalCompliance\nwhere TIMESTAMP > CURRENT_DATE() - interval 1 month\norder by TIMESTAMP asc ;\n"
    }
   ]
  },
  {
   "title": "Patch management state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select count(*) as \"Nodes up-to-date\", TIMESTAMP from nodes where software_updates = 0 group by timestamp order by timestamp desc limit 1;"
    },
    {
     "dataset": "grafana",
     "rawSql": "\nselect count(*) as \"Nodes that have security updates available\" from nodes where software_security_updates != 0 group by timestamp order by timestamp desc limit 1;"
    },
    {
     "dataset": "grafana",
     "rawSql": "select count(*) as \"Nodes that need to be updated\" from nodes where software_updates != 0 group by timestamp order by timestamp desc limit 1;;"
    }
   ]
  },
  {
   "title": "Global compliance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select timestamp as date, global_compliance as 'Global compliance' from globalCompliance;"
    }
   ]
  },
  {
   "title": "OS version repartition",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT\n    CASE\n        WHEN os_name LIKE 'Windows%' THEN os_name\n        ELSE CONCAT(os_name, ' ', os_version)\n    END AS OS,\n    COUNT(*) AS count\nFROM\n    nodes\nGROUP BY\n    OS;\n"
    }
   ]
  },
  { "title": "Compliance breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Top 5 Non-Compliant Nodes by Rule Compliance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "WITH lowestComplianceNodes AS (\n    -- Select the 5 nodes with the lowest compliance\n    SELECT id\n    FROM nodes\n    WHERE timestamp = (SELECT MAX(timestamp) FROM nodes)\n    ORDER BY compliance ASC  -- Use ASC for lowest compliance\n    LIMIT 5\n)\n-- Fetch the rule compliance for these nodes\nSELECT\n    n.id,\n    n.hostname,\n    n.compliance as nodes_compliance,\n    nir.rule_id,\n    r.name,\n    nir.compliance as rule_compliance\n\nFROM\n    nodes n\n\nJOIN\n    nodesInRules nir ON n.id = nir.id\nJOIN\n    lowestComplianceNodes lcn ON n.id = lcn.id\nJOIN\n    rules r on r.id = nir.rule_id\nWHERE nir.compliance < 100\n\n\n"
    }
   ]
  },
  {
   "title": "Rules compliance over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT timestamp AS date, id, name, compliance AS 'Rules compliance' FROM rules ;\n"
    }
   ]
  },
  {
   "title": "Directives having loops in configurations",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "WITH recentTimestamp AS (\n    SELECT DISTINCT\n        timestamp as date\n    FROM\n        directives\n    ORDER BY date DESC limit 2\n)\nSELECT  r.name as \"Directive name\", AVG(r.success_repaired) as \"Proportion of 'Repaired' (%)\"\nFROM\n    directives r\nJOIN\n    recentTimestamp rt ON r.timestamp = rt.date\nWHERE\n  r.success_repaired != 0\nGROUP BY\n    r.id, r.name\n"
    }
   ]
  },
  {
   "title": "Nodes having loops in configurations",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 36 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "WITH recentTimestamp AS (\n    SELECT DISTINCT\n        timestamp as date\n    FROM\n        nodes\n    ORDER BY date DESC limit 2\n)\nSELECT  n.hostname as \"Hostname\", AVG(n.success_repaired) as \"Proportion of 'Repaired' (%)\"\nFROM\n    nodes n\nJOIN\n    recentTimestamp rt ON n.timestamp = rt.date\nWHERE\n  n.success_repaired != 0\nGROUP BY\n    n.id, n.hostname\n"
    }
   ]
  },
  {
   "title": "Patch management & Vulnerabilities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "Last campaign event results",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select name, end_date, updated_nodes as 'Nodes updated', failed_nodes as 'Nodes having errors during campaign' \nfrom grafana.campaignEvents \nwhere state='finished' \nORDER BY end_date DESC limit 1;"
    }
   ]
  },
  {
   "title": "Top 10 nodes with security updates available",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 42 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select hostname, software_security_updates as 'Security updates available' \nfrom nodes \nWHERE timestamp = (SELECT MAX(timestamp) FROM nodes)\nORDER BY software_security_updates desc limit 10;\n"
    }
   ]
  },
  {
   "title": "Campaign events over time",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select  DATE_FORMAT(STR_TO_DATE(start_date, '%Y-%m-%dT%H:%i:%sZ'), '%Y-%m')   as 'Month', \nsum(failed_pkg) AS 'Failed updates',  \nSUM(updated_pkg) as 'Updated packages'\nfrom grafana.campaignEvents\nGROUP BY Month\nORDER BY Month asc;"
    }
   ]
  },
  {
   "title": "Campaign events for each month over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select  DATE_FORMAT(STR_TO_DATE(start_date, '%Y-%m-%dT%H:%i:%sZ'), '%Y-%m-01') as 'Date', sum(failed_pkg) as 'Failed updates',  SUM(updated_pkg) as 'Updated packages'\nfrom grafana.campaignEvents\nGROUP BY Date\nORDER BY Date;"
    }
   ]
  },
  {
   "title": "Corrected CVEs over the last month",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select count(cve_id) as 'Corrected CVEs last month' from grafana.cves\nwhere last_presence_check > current_date() - interval 1 MONTH\nAND last_presence_check != (select last_presence_check from cves ORDER BY last_presence_check desc limit 1);"
    },
    {
     "dataset": "grafana",
     "rawSql": "select count(cve_id) as 'CVEs still active' from grafana.cves\nwhere last_presence_check > current_date() - interval 1 month;"
    }
   ]
  },
  {
   "title": "Average duration (in days) to patch a high or critical CVE over the last 3 months",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select AVG(DATEDIFF(last_presence_check, first_appearance)) as 'Days' from grafana.cves\nwhere last_presence_check != (select last_presence_check from cves ORDER BY last_presence_check desc limit 1)\n and first_appearance > current_date() - interval 3 month;\n"
    }
   ]
  },
  {
   "title": "High & critical CVEs variation over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 2, "y": 73 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select last_presence_check as date, (select count(cve_id) from cves where first_appearance <=date and last_presence_check>=date and severity='high') as 'High severity CVEs' from cves group by date order by date;"
    },
    {
     "dataset": "grafana",
     "rawSql": "select last_presence_check as date, (select count(cve_id) from cves where first_appearance <=date and last_presence_check>=date and severity='critical') as 'Critical severity CVEs' from cves group by date order by date;"
    }
   ]
  },
  {
   "title": "Critical & High CVEs variation over time for each node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 2, "y": 82 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select timestamp, hostname, high_cves + critical_cves as 'Critical & High CVEs' from nodes ;"
    }
   ]
  },
  {
   "title": "Number of campaigns by campaign type in real time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT campaign_type, count(*) FROM grafana.campaigns group by campaign_type;\n"
    }
   ]
  },
  {
   "title": "Frequency of active campaigns in real time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 91 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select frequency, count(*) from grafana.campaigns \nwhere status='enabled'\ngroup by frequency;\n\n"
    }
   ]
  },
  {
   "title": "Critical & High CVEs for each node",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select hostname, critical_cves+ high_cves \nfrom nodes where critical_cves + high_cves > 5 and timestamp = (SELECT MAX(timestamp) FROM nodes)\nUnion select 'others', SUM( critical_cves + high_cves) \nfrom nodes \nwhere critical_cves + high_cves <= 5 and timestamp = (SELECT MAX(timestamp) FROM nodes)\ngroup by others;"
    }
   ]
  },
  {
   "title": "Critical & High  CVEs for each node",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select hostname, critical_cves+ high_cves \nfrom nodes where critical_cves + high_cves > 5 and timestamp = (SELECT MAX(timestamp) FROM nodes)\nUnion select 'others', SUM( critical_cves + high_cves) \nfrom nodes \nwhere critical_cves + high_cves <= 5 and timestamp = (SELECT MAX(timestamp) FROM nodes)\ngroup by others;"
    }
   ]
  }
 ]
}